#pragma config(Motor,  motorB,          motorRight,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorA,          motorLeft,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.c"
#include "position.c"
#include "movement.c"

float notes[8] = {1046.50, 1174.66, 1318.51, 1396.91, 1567.98, 1760.00, 1975.53, 2093.00};
void fanfare() {
	playTone(notes[7], 15); wait1Msec(150);
	playTone(notes[7], 15); wait1Msec(150);
	playTone(notes[7], 15); wait1Msec(150);
	playTone(notes[7], 45); wait1Msec(450);
	playTone(1661.22, 45); wait1Msec(450);
	playTone(1864.66, 45); wait1Msec(450);
	playTone(notes[7], 15); wait1Msec(150);
	wait1Msec(150);
	playTone(1864.66, 15); wait1Msec(150);
	playTone(notes[7], 90); wait1Msec(900);
}

task main()
{
	motor[motorRight] = 20;
  initConfig(JIMMY);
  initPosition(false);

  while (true) {}
}
