#pragma config(Sensor, S4,     redButton,      sensorEV3_Touch)
#pragma config(Motor,  motorA,          motorRight,    tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorLeft,     tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.c"
#include "position.c"
#include "movement.c"

float notes[8] = {1046.50, 1174.66, 1318.51, 1396.91, 1567.98, 1760.00, 1975.53, 2093.00};
unsigned int currentNote = 0;

void beep() {
	playTone(notes[currentNote], 10);
	currentNote += 1;
	if (currentNote == 9)
		currentNote = 0;
}

void fanfare() {
	playTone(notes[7], 15); wait1Msec(150);
	playTone(notes[7], 15); wait1Msec(150);
	playTone(notes[7], 15); wait1Msec(150);
	playTone(notes[7], 45); wait1Msec(450);
	playTone(1661.22, 45); wait1Msec(450);
	playTone(1864.66, 45); wait1Msec(450);
	playTone(notes[7], 15); wait1Msec(150);
	wait1Msec(150);
	playTone(1864.66, 15); wait1Msec(150);
	playTone(notes[7], 90); wait1Msec(900);
}

task emergencyStop() {
	while (SensorValue[redButton] == 0) { wait1Msec(20); }
	stopAllTasks();
}

task displayPos() {
	struct PosData pos;
	while (true) {
		getPosition(&pos);
		displayBigTextLine(1, "%5.1f %5.1f %5.1f", pos.x, pos.y, pos.orientation);
		wait1Msec(50);
	}
}

task main() {
  initConfig(TULLIUS);
  initPosition(true);

  while (SensorValue[redButton] == 0) { wait1Msec(20); }
  while (SensorValue[redButton] == 1) { wait1Msec(20); }
  wait1Msec(100);
  startTask(emergencyStop);
  startTask(displayPos);

  PosData pos;

  /*
	moveTo(-400, -400);
	moveTo(-800, -400);
	moveTo(-500, 470, 90);
	*/

	setSoundVolume(15);
	moveTo(200, 0);
	moveTo_backwards(0, 0);
	rotateTo(180);
	rotateTo(0);
	while (getMovementState() != NOMVT) { wait1Msec(20); }
	fanfare();
}
