#pragma config(Sensor, S3,     redButton,      sensorEV3_Touch)
#pragma config(Motor,  motorA,          motorRight,    tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorLeft,     tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.c"
#include "position.c"
#include "movement.c"

float notes[8] = {1046.50, 1174.66, 1318.51, 1396.91, 1567.98, 1760.00, 1975.53, 2093.00};
unsigned int currentNote = 0;

void beep() {
	playTone(notes[currentNote], 10);
	currentNote += 1;
	if (currentNote == 9)
		currentNote = 0;
}

void fanfare() {
	playTone(notes[7], 15);
	playTone(notes[7], 15);
	playTone(notes[7], 15);
	playTone(notes[7], 45);
	playTone(1661.22, 45);
	playTone(1864.66, 45);
	playTone(notes[7], 30);
	playTone(1864.66, 15);
	playTone(notes[7], 90);
}

task main() {
  initConfig(TULLIUS);
  initPosition(true);
  PosData const* pos = NULL;

  /*
	moveTo_forceStraight(-400, -400);
	moveTo_forceStraight(-800, -400);
	moveTo_forceStraight(-500, 470, 90);
	straight(-200); */

	setSoundVolume(10);


	moveTo(500, 500);

	moveTo(1000, 0);

	rotateTo(180);

	rotateTo(0);

	moveTo(0, 0);
	wait1Msec(2000);
	pauseMovement();
	wait1Msec(2000);
	resumeMovement();

	rotateTo(0);

	moveTo(2000, 0);
	wait1Msec(2000);
	abortMovement();

	moveTo(0, 0);

	rotateTo(0);
	while(getMovementState() != NOMVT) {wait1Msec(10);}
	fanfare();
	while(true) {
		getPosition(&pos);
		wait1Msec(10);
		displayBigTextLine(1, "%5.1f %5.1f %5.1f", pos->x, pos->y, pos->orientation);
	}
}
