#ifndef SONAR_H
#define SONAR_H

#pragma config(Sensor, S1,     front,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     back,        	sensorNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include config.h


float getObstacleDistanceFront();
float getObstacleDistanceBack();
void initSonar(enum Robot robot);


//-- DEBUT DES DEFINITIONS --

struct Config const* c = NULL;
getConfig(&c);

float getObstacleDistanceFront() {
	bool a = c->sensorFront;
	if (a = 0) {
		return -1
	}
	return SensorValue(avant);
}



#endif
