#ifndef SONAR_H
#define SONAR_H

#pragma config(Sensor, S1,     front,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     back,        	sensorNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include config.h


float getObstacleDistanceFront();
float getObstacleDistanceBack();


//-- DEBUT DES DEFINITIONS --

float getObstacleDistanceFront() {
	struct Config const* c = NULL;
	getConfig(&c);
	if (c->sensorFront == 0)
		return -1
	else
		return 10*SensorValue(front);
}

float getObstacleDistanceBack() {
	struct Config const* c = NULL;
	getConfig(&c);
	if (c->sensorBack == 0)
		return -1
	else
		return 10*SensorValue(back);
}


#endif
