#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_Matrix_S1_1, motorRight,    tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_2, motorE,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_3, motorLeft,     tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_4, motorG,        tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int speedMeasureInterval = 1; //ms, temps entre deux mesures.
const int speedWindow = 25; //durée de la fenêtre glissante pour la vitesse (+grand => meilleure résolution mais plus de moyennage)
														//en multiples de speedMeasureInterval.
int encoders[speedWindow];

const int speedsMeasured = 1000; //Nombre de vitesses relevées
float speeds[speedsMeasured]; //encode / ms

void measureSpeed() {
	speeds[0] = 0;
	encoders[0] = nMotorEncoder[motorRight];

	unsigned int i = 1;
	unsigned int relative_i = 1;
	clearTimer(T1);

	while (i < speedsMeasured) {
		if (time1[T1] >= i * speedMeasureInterval) {
			relative_i = i%speedWindow;
			int currentEncoder = nMotorEncoder[motorRight];

			if (i > speedWindow)
					speeds[i] = currentEncoder;
					//speeds[i] = (float)(currentEncoder - encoders[relative_i]) / (speedMeasureInterval * speedWindow);
			else
					speeds[i] = currentEncoder;
					//speeds[i] = (float)(currentEncoder - encoders[0]) / (speedMeasureInterval * i);

			encoders[relative_i] = currentEncoder;
			i++;
		}
	}
}

task main() {
	motor[motorLeft] = -20;
	motor[motorRight] = 20;
	measureSpeed();
	motor[motorLeft] = 0;
	motor[motorRight] = 0;

	TFileHandle handler;
	TFileIOResult IOResult;
	string toWrite = "motorTest.txt";
	short fileSize = speedsMeasured * 14 + 1000;

	Delete("motorTest.txt", IOResult);
	OpenWrite(handler, IOResult, toWrite, fileSize);

	stringFormat(toWrite, "speeds = [%12.3f, ", speeds[0]);
	WriteText(handler, IOResult, toWrite);
	for (int i = 1; i < speedsMeasured - 1; i++) {
		stringFormat(toWrite, "%6.3f, ", speeds[i]);
		WriteText(handler, IOResult, toWrite);
	}
	stringFormat(toWrite, "%6.3f]", speeds[speedsMeasured - 1]);
	WriteText(handler, IOResult, toWrite);
	Close(handler, IOResult);
}
