#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_Matrix_S1_1, motorRight,    tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_2, motorE,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_3, motorLeft,     tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_4, motorG,        tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int msBetweenMeasures = 1;
const int measures = 1000;
int encodes[measures];

task main() {
	for (int speed = 10; speed < 51; speed += 10) {
		TFileHandle handler;
		TFileIOResult IOResult;
		string toWrite;
		stringFormat(toWrite, "motorTest_%i.txt", speed);
		short fileSize = measures * 8 + 1000;

		motor[motorLeft] = -speed;
		motor[motorRight] = speed;
		clearTimer(T1);
		for (int i = 0; i < measures; i++) {
			while(time1[T1] < i * msBetweenMeasures) {}
			encodes[i] = nMotorEncoder[motorRight];
		}
		motor[motorLeft] = 0;
		motor[motorRight] = 0;

		Delete(toWrite, IOResult);
		OpenWrite(handler, IOResult, toWrite, fileSize);

		stringFormat(toWrite, "encodes = [%i, ", encodes[0]);
		WriteText(handler, IOResult, toWrite);
		for (int i = 1; i < measures - 1; i++) {
			stringFormat(toWrite, "%i, ", encodes[i]);
			WriteText(handler, IOResult, toWrite);
		}
		stringFormat(toWrite, "%i]", encodes[measures - 1]);
		WriteText(handler, IOResult, toWrite);
		Close(handler, IOResult);
	}
}
