#pragma config(Sensor, S4,     redButton,      sensorEV3_Touch)
#pragma config(Motor,  motorA,          motorRight,    tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorLeft,     tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define sensorFront S2
#define sensorBack S1

#include "config.c"
#include "position.c"
#include "movement.c"
#include "sonar.c"

float notes[8] = {1046.50, 1174.66, 1318.51, 1396.91, 1567.98, 1760.00, 1975.53, 2093.00};
unsigned int currentNote = 0;

void beep() {
	playTone(notes[currentNote], 10);
	currentNote += 1;
	if (currentNote == 8)
		currentNote = 0;
}

void fanfare() {
	playTone(notes[7], 15); wait1Msec(150);
	playTone(notes[7], 15); wait1Msec(150);
	playTone(notes[7], 15); wait1Msec(150);
	playTone(notes[7], 45); wait1Msec(450);
	playTone(1661.22, 45); wait1Msec(450);
	playTone(1864.66, 45); wait1Msec(450);
	playTone(notes[7], 15); wait1Msec(150);
	wait1Msec(150);
	playTone(1864.66, 15); wait1Msec(150);
	playTone(notes[7], 90); wait1Msec(900);
}

task emergencyStop() {
	while (SensorValue[redButton] == 0) { wait1Msec(20); }
	stopAllTasks();
}

task displayPos() {
	struct PosData pos;
	while (true) {
		getPosition(&pos);
		displayBigTextLine(1, "X : %6.2f", pos.x);
		displayBigTextLine(3, "Y : %6.2f", pos.y);
		displayBigTextLine(5, "O : %6.2f", pos.orientation);
		wait1Msec(50);
	}
}

task main() {
  initConfig(TULLIUS);
  initPosition(false);
  setSoundVolume(30);

  while (SensorValue[redButton] == 1) { wait1Msec(20); }
  wait1Msec(100);
  startTask(emergencyStop);
  startTask(displayPos);
  startTask(avoidObstacles);

  PosData pos;

	moveTo(-400, -400);
	moveTo(-850, -400);
	moveTo(-600, 0);
	rotateTo(90);
	moveTo(-500, 450);
	moveTo_backwards(-500, -1000);
	moveTo(-100, -1000);
	moveTo(-100, -700);
	moveTo(-400, 600);
	while (getMovementState() != NOMVT) {wait1Msec(20);}
	fanfare();
}
