#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_Matrix_S1_1, motorD,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_2, motorLeft,     tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_3, motorF,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_4, motorRight,    tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.c"
#include "position.c"
#include "movement.c"

task displayPos() {
	struct PosData pos;
	while (true) {
		wait1Msec(20);
		getPosition(&pos);
		nxtDisplayBigTextLine(1, "X %5.1f", pos.x);
		nxtDisplayBigTextLine(3, "Y %5.1f", pos.y);
		nxtDisplayBigTextLine(5, "O %5.1f", pos.orientation);
	}
}

task main()
{
  initConfig(OBELIX);
  initPosition(true);
  startTask(displayPos);
  moveTo(1000, 0);

  while (true) {}
}
