#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_Matrix_S1_1, motorLeft,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_2, motorE,     tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_3, motorRight,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_4, motorG,    tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.c"
#include "position.c"
#include "movement.c"

task displayPos() {
	struct PosData pos;
	while (true) {
		wait1Msec(200);
		getPosition(&pos);
		displayBigTextLine(1, "X %5.1f", pos.x);
		displayBigTextLine(3, "Y %5.1f", pos.y);
		displayBigTextLine(5, "O %5.1f", pos.orientation);
		writeDebugStreamLine("X:%5.1f Y:%5.1f O:%5.1f", pos.x, pos.y, pos.orientation);
	}
}

task main()
{
  initConfig(OBELIX);
  initPosition(true);
 	startTask(displayPos);

 	moveTo_backward(300, 0);
 	moveTo(0, 0);
 	rotateTo(180);
 	moveTo(0, 100);
 	moveTo(0, 0);
 	rotateTo(0);

  while (true) {wait10Msec(100);}
}
