#pragma config(Sensor, S4,     redButton,      sensorEV3_Touch)
#pragma config(Motor,  motorA,          motorRight,    tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorB,          motorLeft,     tmotorEV3_Medium, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define sensorFront S2
#define sensorBack S1

float notes[8] = {1046.50, 1174.66, 1318.51, 1396.91, 1567.98, 1760.00, 1975.53, 2093.00};
unsigned int currentNote = 0;

void beep() {
	playTone(notes[currentNote], 10);
	currentNote += 1;
	if (currentNote == 8)
		currentNote = 0;
}

#include "config.c"
#include "position.c"
#include "movement.c"
#include "sonar.c"

void fanfare() {
	playTone(notes[7], 15); wait1Msec(150);
	playTone(notes[7], 15); wait1Msec(150);
	playTone(notes[7], 15); wait1Msec(150);
	playTone(notes[7], 45); wait1Msec(450);
	playTone(1661.22, 45); wait1Msec(450);
	playTone(1864.66, 45); wait1Msec(450);
	playTone(notes[7], 15); wait1Msec(150);
	wait1Msec(150);
	playTone(1864.66, 15); wait1Msec(150);
	playTone(notes[7], 90); wait1Msec(900);
}

task emergencyStop() {
	while (SensorValue[redButton] == 0) { wait1Msec(20); }
	stopAllTasks();
}

task displayPos() {
	struct PosData pos;
	while (true) {
		getPosition(&pos);
		displayBigTextLine(1, "X : %6.2f", pos.x);
		displayBigTextLine(3, "Y : %6.2f", pos.y);
		displayBigTextLine(5, "O : %6.2f", pos.orientation);
		wait1Msec(50);
	}
}

task main() {
  initConfig(TULLIUS);
  initPosition(true);
  setSoundVolume(30);

	while (SensorValue[redButton] == 1) { wait1Msec(20); }
  wait1Msec(100);
	startTask(emergencyStop);
	startTask(displayPos);
	startTask(avoidObstacles);

  PosData pos;

	moveTo(-400, -400);
	moveTo(-850, -400);
	moveTo(-600, 0);
	rotateTo(90);
	moveTo(-500, 450);
	moveTo_backward(-500, -500);
	rotateTo(180);
	moveTo(-2200, -500);
	moveTo(-2200, 100);
	rotateTo(0);
	moveTo(-300, 100);
	while (true) {wait1Msec(20);}
}
